// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlXkik25wySxum5pU_RZYbt-mNBjXsbE',
    appId: '1:62665370426:web:432ccb5e18b734f8273e03',
    messagingSenderId: '62665370426',
    projectId: 'elfid-5cd8a',
    authDomain: 'elfid-5cd8a.firebaseapp.com',
    storageBucket: 'elfid-5cd8a.firebasestorage.app',
    measurementId: 'G-QK1H6KF2B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVjI_1JbGtQ5bI76qNlozfj9bDd-_hg9M',
    appId: '1:62665370426:android:9b3ed912c6104b6a273e03',
    messagingSenderId: '62665370426',
    projectId: 'elfid-5cd8a',
    storageBucket: 'elfid-5cd8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiJ_gPaYFVD0YlKRgPBtZhbLpLXv8nTBE',
    appId: '1:62665370426:ios:58bea01dcbc0eb05273e03',
    messagingSenderId: '62665370426',
    projectId: 'elfid-5cd8a',
    storageBucket: 'elfid-5cd8a.firebasestorage.app',
    iosBundleId: 'com.elikiasolutions.perfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiJ_gPaYFVD0YlKRgPBtZhbLpLXv8nTBE',
    appId: '1:62665370426:ios:58bea01dcbc0eb05273e03',
    messagingSenderId: '62665370426',
    projectId: 'elfid-5cd8a',
    storageBucket: 'elfid-5cd8a.firebasestorage.app',
    iosBundleId: 'com.elikiasolutions.perfect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlXkik25wySxum5pU_RZYbt-mNBjXsbE',
    appId: '1:62665370426:web:607105ab83b4bb8b273e03',
    messagingSenderId: '62665370426',
    projectId: 'elfid-5cd8a',
    authDomain: 'elfid-5cd8a.firebaseapp.com',
    storageBucket: 'elfid-5cd8a.firebasestorage.app',
    measurementId: 'G-4ZNZ8HK5QD',
  );
}
